spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web_urine?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: zmall
    password: zhin2929
    driver-class-name: com.mysql.jdbc.Driver

  session:
    store-type: none
    timeout: 120




  messages:
    basename: i18n/messages
  mvc:
    locale: zh_CN
  freemarker:
    cache: false
    suffix: .html
    settings:
      auto_import: >
        /spring.ftl as spring, /layout/head.html as headTemplate,
        /layout/footer.html as footerTemplate, /layout/nav.html as navTemplate,
        /layout/float_btn.html as floatTemplate, /layout/qrcode.html as qrcodeTemplate
      datetime_format: yyyy-MM-dd HH:mm:ss
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss





mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: me.zhin.weburine.dao


zhin:
  security:
    browser:
      signInPage: /login
      signUpUrl: /signUp
      signInResponseType: REDIRECT
      rememberMeSeconds: 294000
      signOutUrl: /index
      singInSuccessUrl: /index


debug: false


security:
  oauth2:
    client:
      client-id: UrineApp
      client-secret: UrineAppsecret
server:
  port: 8089





